Code review request
jrai0792/the-next-web-clone pull request #2
Opened 2020-08-11 13:34 UTC by jrai0792

-Initialize the project with index.html, style.css, and linters setup.
-Style basic structure.
-Add the HTML structure.
-Finish style basic structure.
-Started with media queries.
-Added content and style to the navbar and gallery section.
-Add element and style to the latest news.
-Add content and style for the Most popular section.
-Add content and style to the footer section and hover effect.
-Add content and style to the latest deals and add content to the footer.
-Add changes to media queries.
-Add media queries for the gallery, latest news, and funding section.
-Add media queries for the nav-bar, deals, and footer section.
-Add media queries for a tablet screen.
-Updated the README.md file.

2020-08-11 15:50 UTC, kitpao requested changes
# 👋 Hello @jrai0792 and @Adewunmi97 

The organization in your CSS code is pretty nice 💯 and it is a nice touch you took the care to add hover effects 🌟 Please check below to see required changes 🔽 

**_Note:_** All the **[OPTIONAL]** are **not required** in order to approve your project but are personal suggestions to improve your coding experience

- [ ] **[OPTIONAL]** Some of your images look stretched out, you can correct this problem by adding `object-fit: cover` in their styling, this way the proportions of the image will be respected

- [ ] Please Edit the title of your pull request to be more meaningful and related to the project as [requested in pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/), like in the example:
![image](https://user-images.githubusercontent.com/53256139/88913714-1e2c5200-d227-11ea-86b8-c57297465ea3.png)

- [ ] For next time, remember to write your commits in the imperative tense, as stated in [the article pointed in pathwright](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/)

### About your implementation

- [ ] CSS styles should use [media queries](https://www.w3schools.com/css/css_rwd_mediaqueries.asp) for 2 breakpoints ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/responsive_design/breakpoints_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540217/))
    - No small breakpoint as it is mobile-first and the base styles are for the mobile screen. ([Screenshot on mobile-first approach](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/responsive_design/mobile_first.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540217/))
    - medium: min-width around 768px
    - large: min-width 1024px
So that you have the minimum trouble fixing this, as a personal suggestion I would recommend you that first, you put all desktop-related code inside a media query with min-width of 1024 and test that everything works fine, then proceed to make the movements to put your mobile-related code inside the default CSS.

- [ ] **OPTIONAL** Note that the sizing in your elements get weird because you are using vh units for the height, so when the height is small,  your elements overlap. I would recommend using em, rem or px for heights. For widths, it's ok to use vw because you are already taking care of them with your media queries

### Mobile screen:
- [ ] Please check and fix the following:
![image](https://user-images.githubusercontent.com/53256139/89908426-7a8e5a80-dbb3-11ea-99c2-05bfadaaf940.png)
![image](https://user-images.githubusercontent.com/53256139/89909628-e6bd8e00-dbb4-11ea-835c-2e3e56b5ac3f.png)
![image](https://user-images.githubusercontent.com/53256139/89911467-1372a500-dbb7-11ea-97c1-c65549e12888.png)
![image](https://user-images.githubusercontent.com/53256139/89914264-613cdc80-dbba-11ea-9992-7342b49db387.png)

### Tablet screen:
- [ ] Please check and fix the following:
![image](https://user-images.githubusercontent.com/53256139/89914677-f50ea880-dbba-11ea-8cd9-1cec050321ac.png)
![image](https://user-images.githubusercontent.com/53256139/89914964-62bad480-dbbb-11ea-9e65-ba39311a1453.png)
![image](https://user-images.githubusercontent.com/53256139/89915177-a7467000-dbbb-11ea-9a41-58ecbb2750e9.png)
![image](https://user-images.githubusercontent.com/53256139/89915449-00ae9f00-dbbc-11ea-976a-97d997c20dc9.png)

### Desktop screen:
- [ ] Please check and fix the following:
![image](https://user-images.githubusercontent.com/53256139/89916033-b8dc4780-dbbc-11ea-8fc8-8291e08e0cd8.png)

You did nicely on desktop 🏅 

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-08-11 15:50 UTC, kitpao commented on assets/style.css
> +
- [ ] You are repeating the same rules in different parts of your CSS. For good coding practices ([check this link](https://speckyboy.com/good-bad-css-practices)), follow the DRY rule (Don't repeat yourself).
![image](https://user-images.githubusercontent.com/53256139/89356769-33203f80-d684-11ea-8a2b-7776e5a73811.png). You are repeating rules as `text-decoration: none;`, `display: none;`, `list-style: none;`, etc

2020-08-12 15:12 UTC, bertil291utn requested changes
## **Status:** Changes requested 🟠  :shipit:? Not yet.

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitHub Flow you have a professional README file. 

However, in order to accomplish as the actual page, you required to do these changes, listed below:

### General requirements 

- [ ] Remove extra padding when you large screen approach   

![image](https://user-images.githubusercontent.com/24902525/90030037-2fdb1400-dc81-11ea-8fcd-f46b19182850.png)

### Specific Req.

| Section/Screen                             | Large(1024px) | Medium(768px) | Small |
| :----------------------------------------- | :---: | :----: | :---: |
| Navigation bar                             |   1    |        |       |
| Top 3 articles section                     |       |        |       |
| Latest news section                        |    2   |        |       |
| Latest Funding section                     |   3    |        |    7   |
| Categories (Apps, Gear, Tech, etc) section |   4    |        |       |
| Latest deals section                       |    5   |        |       |
| Footer                                     |       |        | 8      |
###### This table is given each section with his screen width approach, each issue is given by number below this table

1. About links should be more in the left

![image](https://user-images.githubusercontent.com/24902525/90029729-ceb34080-dc80-11ea-8b8e-984cc134af9c.png)

2. Remove extra padding you have with 1024px screens

| ACTUAL WEB PAGE | YOURS |
| :-------------: | :---: |
| ![image](https://user-images.githubusercontent.com/24902525/90029869-facec180-dc80-11ea-906e-697374a44ad2.png) | ![image](https://user-images.githubusercontent.com/24902525/90029850-f3a7b380-dc80-11ea-9193-6b65323d29e0.png) |

3. Links  should be after the title 

| ACTUAL WEB PAGE | YOURS |
| :-------------: | :---: |
| ![image](https://user-images.githubusercontent.com/24902525/90030212-66189380-dc81-11ea-9396-7b6e228459b2.png) | ![image](https://user-images.githubusercontent.com/24902525/90030153-5436f080-dc81-11ea-8af4-55ceaa0649da.png) |

4. Each article is overlapping, please fix that

![image](https://user-images.githubusercontent.com/24902525/90030316-87797f80-dc81-11ea-87ce-8ae5a2e4b10b.png)

5. Latest deals section is overlapping with footer

![image](https://user-images.githubusercontent.com/24902525/90030424-a841d500-dc81-11ea-8425-6e9e1cd280da.png)

6. Please fix all medium screens approach, elements should have an order
![image](https://user-images.githubusercontent.com/24902525/90030819-1e463c00-dc82-11ea-8d7c-681c9fd83806.png)

7. Same this section is overlapping to another one

![image](https://user-images.githubusercontent.com/24902525/90030970-4e8dda80-dc82-11ea-966b-b7263f16c616.png)

8. The copyright is missing

![image](https://user-images.githubusercontent.com/24902525/90031145-8432c380-dc82-11ea-80be-c90b5f988215.png)

### OPTIONAL

- It'd be great if you use just one CSS file adding media queries in the same file

```CSS
/* all my rules */

@media (min-width 1024){
}

```

### Summary

- The complete page (small, medium and large screens) has overlapping section issues, please fix them
- Medium screens approach is completely messed, please fix all medium screens approach 
-  Don't forget to work with inline comments below this comment box.

***

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-08-12 15:12 UTC, bertil291utn commented on assets/tablet.css
> +    width: 100%;
## Using the Same Rule Repetitively[1]
- [ ] You already have `display:flex` pro[erty, please use it.
- [ ] Delete all your `display:flex;` properties in entire CSS file
- [ ] Add your HTML tags


**Html file**

```HTML
<div class="flex">
```
**Note:** Do this change to all properties in this file 

<hr>

_[1] [Good and bad  CSS practices](https://speckyboy.com/good-bad-css-practices/)_

2020-08-12 15:12 UTC, bertil291utn commented on assets/style.css
> +  height: 608.8vh;
## Using the Same Rule Repetitively[1]
- [ ] Create a class once and the use in each HTML tag where you need it.
- [ ] Delete all your `background-color: white;` and `background-color: #fff;` properties in entire CSS file, and create just one global for both of them
- [ ] Add your HTML tags


**Example:**

**CSS file**

```CSS
.white-background{
  background-color: #fff;
}
```
**Html file**

```HTML
<div class="white-background">
```
**Note:** Do this change to all properties in this file 

<hr>

_[1] [Good and bad  CSS practices](https://speckyboy.com/good-bad-css-practices/)_

2020-08-13 17:48 UTC, MuriloRoque requested changes
# Status: Changes Requested :red_circle: 

## Hello @jrai0792 and @Adewunmi97 :wave: 

## Thank you for fixing the requested changes from the previous TSEs, you did an amazing job :clap: :clap: :clap: 

## However, we still have somethings we need to change, please check below:

1) Your about links still need some adjustments. This is how they look like from 1025px to 1100px:

![Screenshot from 2020-08-13 14-19-31](https://user-images.githubusercontent.com/59691171/90166741-10bbaf80-dd71-11ea-8390-b4e13527ce2e.png)
<br>

2) Latest deals section is still overlapping with the Footer on Medium and Large screens:

![Screenshot from 2020-08-13 14-31-42](https://user-images.githubusercontent.com/59691171/90167305-e7e7ea00-dd71-11ea-9b32-815e22e85561.png)
<br>
![Screenshot from 2020-08-13 14-31-53](https://user-images.githubusercontent.com/59691171/90167321-eae2da80-dd71-11ea-93eb-49c74b206c5a.png)

<br>

3) You still need to fix the ordering in this section for Medium screens, they are also overlapping:

![Screenshot from 2020-08-13 14-35-28](https://user-images.githubusercontent.com/59691171/90167694-680e4f80-dd72-11ea-9613-19aab427fe66.png)

<br>

4) In small screens, this section is still overlapping with another:

![Screenshot from 2020-08-13 14-39-06](https://user-images.githubusercontent.com/59691171/90167981-d94e0280-dd72-11ea-9705-1b3ec827cc5d.png)

5) In small screens, parts of your navbar are overlapping with some sections of your page, please fix the alignment:

![Screenshot from 2020-08-13 14-42-38](https://user-images.githubusercontent.com/59691171/90168533-97718c00-dd73-11ea-88e4-00dc4e03b82f.png)


<br>

## Summary
- The entire page (small, medium and large screens) has overlapping section issues, please fix all of them;
- Before submitting for another review, please make the requested changes.
- Please check my comment in your code bellow and good luck!

2020-08-13 17:48 UTC, MuriloRoque commented on index.html
> +    <!-- <link rel="stylesheet" href="assets/bigscreen.css"> -->
Please, remove the commented code if you are not using it.

2020-08-14 05:35 UTC, kitpao commented
Friendly tip: most of your images are overlaping because you use vh, never use vh to position things or they will be moving everytime

2020-08-14 18:46 UTC, kevcap requested changes
# [STATUS] CHANGES REQUIRED♻️

#### Hey girls, good job making the previously required changes, your project it's looking really good, and we're almost done, however, in order to accomplish as the actual page, please implement the changes listed below:
 
 - [ ] Your code is still overlapping from between 768px to 1024px screens, kindly fix that 💪
![review](https://user-images.githubusercontent.com/56762529/90282203-54331e00-de44-11ea-8ab9-814ec0fe97f2.png)
 
**Please make the required changes and resubmit for a new code review once you are ready**

As always, I wish you all the very best and see you both at the top🚀

  

<hr>

👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-08-15 01:00 UTC, lmaldonadoch requested changes
# Changes Required 🥇 🏃‍♂️

## Great job, team!!! 🏆

You have put a lot of effort into this project, we can tell! There are still some requirements that we have not met from previous reviews that are required for your project to be approved. Here we go:

- [ ] [REQUIRED] On the navbar, the yellow banner is still not implemented, please implement it.
![image](https://user-images.githubusercontent.com/59229758/90301955-85bde080-de68-11ea-9e6c-6e90f540f13c.png)

- [ ] [REQUIRED] On medium size, the navbar is still overlapping. Please fix it.
![image](https://user-images.githubusercontent.com/59229758/90301959-8b1b2b00-de68-11ea-9f9f-3dbfbcb37b08.png)

- [ ] [REQUIRED] The sizing of the top 3 news is off, make it more like the original page.
![image](https://user-images.githubusercontent.com/59229758/90301964-98d0b080-de68-11ea-9575-9bb9aa14df95.png)

- [ ] [REQUIRED] The titles of the section below Latest Funding are still overlapping on medium size, please fix this.
![image](https://user-images.githubusercontent.com/59229758/90301979-b43bbb80-de68-11ea-8d3d-ba6359a9b48a.png)

- [ ] [REQUIRED] The navbar on mobile size is also not correctly implemented. Please fix it.
![image](https://user-images.githubusercontent.com/59229758/90301980-b867d900-de68-11ea-9c80-ba8f0bfa0d4d.png)

- [ ] [REQUIRED] There is a huge space between the Categories and Latest Deals section. This happens because you have a fixed size for .most-popular on the mobile CSS file. Hint :bulb: avoid using fixed height for sections.
![image](https://user-images.githubusercontent.com/59229758/90301981-bd2c8d00-de68-11ea-985a-71e23a49db48.png)


- [ ] [OPTIONAL] Your images are a little distorted all around. If you use a div with a background image instead of an image and the appropriate sizing (cover/contain) this can easily be fixed.
![image](https://user-images.githubusercontent.com/59229758/90301977-adad4400-de68-11ea-9035-7d51b51c5fb2.png)



## You have done an amazing job!

<img src="https://media.giphy.com/media/4Vtk42BGiL1T2/giphy.gif" width="250" height="250" />

Don't give up! You are so close! It seems to me like you are having a hard time with the navbar and some positioning; don't be afraid to ask for help! We are here to help you, so don't hesitate

Please implement the required changes, and think about the optional ones.

It was a pleasure reviewing your code,

Happy coding! 💻

Slack: Luis Angel Maldoando
[LinkedIn](https://www.linkedin.com/in/lmaldonadoch/)

2020-08-16 11:11 UTC, kubilaycaglayan requested changes
Hello Team 👋 
Status: Changes Required ♻️ 

Well done 👍  You have applied all the necessary changes. Congratulations.
Thanks for your efforts and time.

Just a little arrangement before moving on ⬇️ 

#### **Navbar layout**
<img width="374" alt="yellowbar" src="https://user-images.githubusercontent.com/60448833/90332946-e0bb1900-dfc9-11ea-9c25-4ad593458796.PNG">

**2 things going on here:**

- [ ]  Yellow bar is half of the page's width. It should be full.

- [ ]  The images coming right after the yellow bar and the yellow bar itself using the same area. There should be some amount of margin or padding to push the images down so that the users can see the images as a whole.

That's it.
With all my respect... 🙏

2020-08-16 12:01 UTC, kevcap approved these changes
# [STATUS] PROJECT APPROVED 🍾

### Hello again girls! Good news, your project got approved! Congratulations team! 🐱‍👓
![giphy4](https://user-images.githubusercontent.com/56762529/90333755-c3bd2080-df9e-11ea-80ae-6ebabcc74166.gif)

_**Great work doing all the requested changes, I'm sure you girls learned a lot while implementing them. Your clone looks nice, you have also followed the best practices throughout the code, so you have my approval to move on!**_ 🥇👌

### You girls can now merge. As always, I wish you the very best and see you both at the top🚀

  

<hr>

👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

2020-08-16 14:12 UTC, merged